### ISSUE TITLE
anyone have this working yet with TEMPerGold_V3.1 ?

### ISSUE THREAD

**Issue by ashmanskas** [urwen/temper#11]
I have not yet looked in depth, but it seems that this repo's temper.py succeeds in identifying my device but not in reading its temperature.  I wonder if this version has changed the command interface somewhat.  Here is what I see:

$ python3 temper.py --verbose
Firmware value: b'54454d506572476f6c645f56332e3120'
Data value: b''
Bus 002 Dev 034 413d:2107 TEMPerGold_V3.1 - - - - - -
$ python3 temper.py --json
[
    {
        "vendorid": 16701,
        "productid": 8455,
        "manufacturer": "",
        "product": "",
        "busnum": 2,
        "devnum": 34,
        "devices": [
            "hidraw1",
            "hidraw2"
        ],
        "firmware": "TEMPerGold_V3.1",
        "hex_firmware": "54454d506572476f6c645f56332e3120",
        "hex_data": ""
    }
]
$

I will try to debug more closely when I have a chance, but I'm posting here just in case someone else has already figured out how to use this version of the dongle with temper.py.

**Comment by maasj** [comment]
I've got one with the same _firmware_ and _hex_firmware_ values and it's working fine for me without needing to do anything special.  The JSON output doesn't match the docs in terms of all the available fields and field names, but it looks like the docs are just a bit out of date.

Not sure what's wrong with your setup.  :(

**Comment by ashmanskas** [comment]
Thank you for following up -- very helpful.  I will need to track this down later.  For the meantime, I found an alternative "TEMPerX_V3.3" device that works perfectly with temper.py.  For the record, here is the --json dump with the new device that works for me:

$ python3 temper.py --json
[
    {
        "vendorid": 16701,
        "productid": 8455,
        "manufacturer": "",
        "product": "",
        "busnum": 2,
        "devnum": 80,
        "devices": [
            "hidraw1",
            "hidraw2"
        ],
        "firmware": "TEMPerX_V3.3",
        "hex_firmware": "54454d506572585f56332e3320202020",
        "hex_data": "8001096c4e200000",
        "internal temperature": 24.12
    }
]
