### ISSUE TITLE
Script for python 2.7

### ISSUE THREAD

**Issue by KhurramFHassan** [urwen/temper#13]
Is it possible to change the script for python 2.7? I would like to run it on OpenWRT and its pyserial package is only for python 2.7. I tried to run temper.py on python 2.7 (with pyserial) and it gave the error:

File "/tmp/temper.py", line 322
    results.append({ **info, **usbread.read() })

Thanks

**Comment by urwen** [comment]
I'd like to avoid supporting Python 2. There is a pull request that will unroll this line:
https://github.com/urwen/temper/pull/10

**Comment by urwen** [comment]
I'm going to close this because Python 2.7 is seriously unsupported and we should be using Python 3 instead.
